package dev.liftorium.domain.workout

import dev.liftorium.core.KoverIgnore
import dev.liftorium.domain.common.WeightUnit
import dev.liftorium.domain.run.ProgramRunId

/**
 * Seed plan for a single workout session, computed by the repository
 * from the loaded program resource tables for the schedule occurrence
 * being started.
 *
 * Responsibilities split:
 *  * `:data` (repository) walks the loaded resource tables
 *    (`loaded_session_template`, `loaded_exercise_group`,
 *    `loaded_prescription_item`, `loaded_set_prescription`,
 *    `loaded_prescription_target`) and resolves the run's
 *    `chosenWeekVariants` to produce a [WorkoutPlan].
 *  * `:domain` use case consumes [WorkoutPlan] and stamps it with
 *    ids, sync metadata, and the `ClientMutationId` for the
 *    start-workout mutation.
 *
 * Keeping the plan as a plain domain DTO (vs. having the use case
 * call back into the loaded entities directly) preserves the
 * "framework-free :domain" boundary enforced by
 * `DomainArchUnitTest`.
 */
@KoverIgnore
public data class WorkoutPlan(
    val programRunId: ProgramRunId,
    val plannedOccurrenceId: String,
    val pinnedProgramVersionId: String,
    val sessionTemplateId: String,
    val exercises: List<WorkoutPlanExercise>,
)

@KoverIgnore
public data class WorkoutPlanExercise(
    val prescriptionItemId: String,
    val exerciseGroupId: String,
    val displayOrder: Int,
    val prescribedExerciseId: String,
    val warmupSetCount: Int,
    val sets: List<WorkoutPlanSet>,
) {
    init {
        require(warmupSetCount >= 0) { "warmupSetCount must be non-negative" }
    }
}

/**
 * One prescribed set from the loaded resource, with all calculation
 * targets already resolved against the run's training maxes.
 *
 * `roleFromResource` is the prescription-side role; the use case
 * forwards it to [SetRole] for the seeded [ActualSet]. Warm-up sets
 * are NOT included here — they are generated by the use case from
 * [WorkoutPlanExercise.warmupSetCount] and always have `prescribedSetId
 * == null` and `role == SetRole.Warmup`.
 */
@KoverIgnore
public data class WorkoutPlanSet(
    val prescribedSetId: String,
    val roleFromResource: SetRole,
    val perSide: Boolean,
    val target: WorkoutPlanTarget,
)

/**
 * The resolved prescription target for one set. All fields are
 * independently nullable so conjunctive prescriptions (percent + RPE,
 * or load + reps + RPE) can carry every component.
 */
@KoverIgnore
public data class WorkoutPlanTarget(
    val referenceType: String?,
    val referenceExerciseId: String?,
    val referenceValue: Double?,
    val referenceUnit: WeightUnit?,
    val percent: Double?,
    val roundingRule: String?,
    val calculatedRawLoad: Double?,
    val displayLoad: Double?,
    val displayLoadUnit: WeightUnit?,
    val targetReps: Int?,
    val targetRpe: Double?,
    val targetRir: Int?,
    val caveats: List<String>,
)
